Wait for openshift build to complete

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -33,8 +33,21 @@ jobs:
           insecure_skip_tls_verify: true
           namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
 
-      - name: Build image
-        run: oc start-build bc/service-billing --follow
+      - name: Start OpenShift Build
+        run: |
+          oc start-build bc/service-billing
+
+      - name: Wait for Build to Complete
+        run: |
+          STATUS=""
+          while [[ $STATUS != "Complete" ]]; do
+            STATUS=$(oc get build bc/service-billing -o jsonpath='{.status.phase}')
+            if [[ $STATUS == "Failed" ]]; then
+              echo "Build failed. Exiting..."
+              exit 1
+            fi
+            sleep 30
+          done
 
       - name: Rollout latest image
-        run: oc rollout latest dc/service-billing --follow
+        run: oc rollout latest dc/service-billing
